# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0002_auto_20161121_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomment',
            old_name='profile',
            new_name='user',
        ),
    ]
