# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproject', '0005_auto_20161130_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='country',
        ),
    ]
